### ISSUE TITLE
Navbar menu button still not working on mobile

### ISSUE THREAD

**Issue by sublimemarch** [deadcity/charsys#146]

**Comment by sublimemarch** [comment]
Take a look at how this was fixed on:

https://github.com/wiliajc87/humblehearts/blob/development/app/views/layouts/_header.html.erb

**Comment by carlydotwebsite** [comment]
as a side note—I mentioned this in Slack—the navbar button actually works on iOS Safari, so it may be an issue exclusive to Android.
