### ISSUE TITLE
Add breadcrumbing where useful

### ISSUE THREAD

**Issue by carlydotwebsite** [deadcity/charsys#165]
We may want to add a breadcrumb navigation for at least the chronicles section, since especially after I add the downtime processing system it'll have some relatively deep links and it would probably be useful to be able to easily get back to the main chronicle page.

**Comment by sublimemarch** [comment]
Rad! Can you give us some examples of what the breadcrumbs would nest like?

**Comment by carlydotwebsite** [comment]
Something like home > chronicle name > manage games > game 1 > downtimes?
