### ISSUE TITLE
Editing Chronicle: When adding new STs, the system re-adds everyone checked but the original ST

### ISSUE THREAD

**Issue by korey-enright** [deadcity/charsys#169]
The Edit Chronicle page has a checkbox format for adding STs. The Owner of the Chronicle has a greyed out checkbox, and it is possible to add new STs by checking a box next to their name and clicking "submit."

When this is done the first time, their name is added once to the list of STs. On further times (e.g., to add more STs), their names are added again, leading to repetition of the names.

**Comment by korey-enright** [comment]
This is probably an issue related to it not needing STs to be unique.

**Comment by carlydotwebsite** [comment]
tbh it's probably also related to me writing this function at like 3:00am also

**Comment by korey-enright** [comment]
yay 3am!
