### ISSUE TITLE
As an ST, I should be able to filter characters by status in chronicle/characters/index.

### ISSUE THREAD

**Issue by sublimemarch** [deadcity/charsys#234]
Default to only showing "active" characters. Maybe there are checkbox facet-y things to select statuses?

**Comment by korey-enright** [comment]
i have exhausted my patience on this issue, I highly recommend using rails and ruby backend logic, because DataTables is literal garbage that doesn't function at all like literally anything should

**Comment by sublimemarch** [comment]
I think we can apply this part of DataTables for our purposes: https://datatables.net/examples/plug-ins/range_filtering.html

Instead of using a range, have the JS match a status.

**Comment by sublimemarch** [comment]
Upon further chatting with Mark who requested this, I've decided to pivot this UI solution. Instead, there will be a table of active characters and a table of inactive characters.
