### ISSUE TITLE
Add touchstones as a data model

### ISSUE THREAD

**Issue by sublimemarch** [deadcity/charsys#237]
What information is associated with a touchstone?

**Comment by sublimemarch** [comment]
Maybe just make this a text field?

**Comment by korey-enright** [comment]
![Uploading Screen Shot 2016-09-11 at 5.17.43 PM.png…]()
<img width="910" alt="screen shot 2016-09-11 at 5 17 13 pm" src="https://cloud.githubusercontent.com/assets/10061697/18420929/b34a4820-7843-11e6-831b-355889cdaf38.png">

**Comment by korey-enright** [comment]
<img width="1095" alt="screen shot 2016-09-11 at 5 25 07 pm" src="https://cloud.githubusercontent.com/assets/10061697/18420994/b4d4c8a4-7844-11e6-94cd-cbc99648d24f.png">
