### ISSUE TITLE
Adding skill specialties adds them a large number of times

### ISSUE THREAD

**Issue by carlydotwebsite** [deadcity/charsys#262]
For some reason adding skill specialties to a character will multiply them when the sheet is saved.

**Comment by eliilek** [comment]
I was curious, but I couldn't replicate this bug, can you be more specific about where you saw it?

**Comment by carlydotwebsite** [comment]
OH SHIT I figured it out, this is an unexpected side-effect of adding autosave, that's why

it's autosaving the new items which haven't yet been assigned IDs, and then continuing to save them as new items because the page doesn't get updated w/ the IDs

we probably need to get back the new skill specialty IDs in the POST response and put them in the hidden forms with javascript

**Comment by carlydotwebsite** [comment]
@eliilek basically, if you create a character, go back to edit, add some skill specialties and wait for a bit and then try and save it, you'll get a large number of duplicate skill specialties

**Comment by carlydotwebsite** [comment]
Additional note—this will probably be an issue with some of the other elements, too, like powers, merits and flaws.

**Comment by eliilek** [comment]
You could probably get around this issue by just binding it to document.unload and only having it happen once, as the user is leaving the page for whatever reason.

**Comment by carlydotwebsite** [comment]
eli is credit to team

**Comment by sublimemarch** [comment]
@eliilek bruh you should just take this issue and put in a PR for it

**Comment by eliilek** [comment]
@stephmarx bruh I wasn't on the team, I couldn't.
