### ISSUE TITLE
View Required: Chronicle Admin Page (chronicles/show)

### ISSUE THREAD

**Issue by korey-enright** [deadcity/charsys#31]
We need a view for Chronicle admins - it should essentially be an overview for the Chron and include links to a "Chronicle's characters" view, associated ruleset views, etc.

**Comment by sublimemarch** [comment]
This is chronicles/show

**Comment by sublimemarch** [comment]
For chronicle owner, needs to include ability to add other sts by their email.

**Comment by korey-enright** [comment]
Cool beans. I will actually get this done tomorrow, I had some things I had to deal with regarding the power temporarily going out.

**Comment by sublimemarch** [comment]
Only allow a user to see:
chronicle/show page if chronicle.sts.include?(current_user)
