### ISSUE TITLE
View Required: Character Show Page

### ISSUE THREAD

**Issue by korey-enright** [deadcity/charsys#40]

**Comment by sublimemarch** [comment]
Wait on this until #41 (create character page) is done.

**Comment by sublimemarch** [comment]
This is very different if character.user == current_user vs character.chronicle.sts.includes?(current_user)

**Comment by sublimemarch** [comment]
Only allow a user to see:
character/show page if character.player == current_user || character.chronicle.sts.include?(current_user)
